version: '3'
services:
  
  #PHP Service
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: php-fpm-laravel
    container_name: app
    user: "1000:1001"
    # restart: unless-stopped
    # tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel-9:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    # restart: unless-stopped
    # tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-9:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  #Postgres Service
  db:
    image: postgres
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
    networks:
      - app-network
    depends_on:
      - app

  #pg admin for phppgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - 5050:80
    networks:
      - app-network
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    # restart: always
    ports:
      - 8081:8080
    networks:
      - app-network
    depends_on:
      - db

#Docker Networks
networks:
  app-network:
    driver: bridge